/** Declaration file generated by dts-gen */

export = perfect_scrollbar;

declare class perfect_scrollbar {
    constructor(element: any, userSettings: any);

    destroy(): void;

    removePsClasses(): any;

    update(): void;

}

